name: Get Unity License

on: workflow_dispatch

jobs:
  requestManualActivationFile:
    name: Activation file request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: game-ci/unity-request-activation-file@v2
        id: getManualLicenseFile
        
      - uses: actions/upload-artifacts@v2
        with: 
          name: Manual activation file
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
          
